sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t larissafabiola/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true larissafabiola/docker-react npm run test